import 'package:freezed_annotation/freezed_annotation.dart';

part 'currency_symbol_model.freezed.dart';
part 'currency_symbol_model.g.dart';

@freezed
class CurrencySymbolModel with _$CurrencySymbolModel {
  factory CurrencySymbolModel({
    required bool? success,
    required Symbols? symbols,
  }) = _CurrencySymbolModel;

  factory CurrencySymbolModel.fromJson(Map<String, dynamic> json) =>
      _$CurrencySymbolModelFromJson(json);
}

@freezed
class Symbols with _$Symbols {
  factory Symbols({
  String? aED,
  String? aFN,
  String? aLL,
  String? aMD,
  String? aNG,
  String? aOA,
  String? aRS,
  String? aUD,
  String? aWG,
  String? aZN,
  String? bAM,
  String? bBD,
  String? bDT,
  String? bGN,
  String? bHD,
  String? bIF,
  String? bMD,
  String? bND,
  String? bOB,
  String? bRL,
  String? bSD,
  String? bTC,
  String? bTN,
  String? bWP,
  String? bYN,
  String? bYR,
  String? bZD,
  String? cAD,
  String? cDF,
  String? cHF,
  String? cLF,
  String? cLP,
  String? cNY,
  String? cOP,
  String? cRC,
  String? cUC,
  String? cUP,
  String? cVE,
  String? cZK,
  String? dJF,
  String? dKK,
  String? dOP,
  String? dZD,
  String? eGP,
  String? eRN,
  String? eTB,
  String? eUR,
  String? fJD,
  String? fKP,
  String? gBP,
  String? gEL,
  String? gGP,
  String? gHS,
  String? gIP,
  String? gMD,
  String? gNF,
  String? gTQ,
  String? gYD,
  String? hKD,
  String? hNL,
  String? hRK,
  String? hTG,
  String? hUF,
  String? iDR,
  String? iLS,
  String? iMP,
  String? iNR,
  String? iQD,
  String? iRR,
  String? iSK,
  String? jEP,
  String? jMD,
  String? jOD,
  String? jPY,
  String? kES,
  String? kGS,
  String? kHR,
  String? kMF,
  String? kPW,
  String? kRW,
  String? kWD,
  String? kYD,
  String? kZT,
  String? lAK,
  String? lBP,
  String? lKR,
  String? lRD,
  String? lSL,
  String? lTL,
  String? lVL,
  String? lYD,
  String? mAD,
  String? mDL,
  String? mGA,
  String? mKD,
  String? mMK,
  String? mNT,
  String? mOP,
  String? mRO,
  String? mUR,
  String? mVR,
  String? mWK,
  String? mXN,
  String? mYR,
  String? mZN,
  String? nAD,
  String? nGN,
  String? nIO,
  String? nOK,
  String? nPR,
  String? nZD,
  String? oMR,
  String? pAB,
  String? pEN,
  String? pGK,
  String? pHP,
  String? pKR,
  String? pLN,
  String? pYG,
  String? qAR,
  String? rON,
  String? rSD,
  String? rUB,
  String? rWF,
  String? sAR,
  String? sBD,
  String? sCR,
  String? sDG,
  String? sEK,
  String? sGD,
  String? sHP,
  String? sLL,
  String? sOS,
  String? sRD,
  String? sTD,
  String? sVC,
  String? sYP,
  String? sZL,
  String? tHB,
  String? tJS,
  String? tMT,
  String? tND,
  String? tOP,
  String? tRY,
  String? tTD,
  String? tWD,
  String? tZS,
  String? uAH,
  String? uGX,
  String? uSD,
  String? uYU,
  String? uZS,
  String? vEF,
  String? vND,
  String? vUV,
  String? wST,
  String? xAF,
  String? xAG,
  String? xAU,
  String? xCD,
  String? xDR,
  String? xOF,
  String? xPF,
  String? yER,
  String? zAR,
  String? zMK,
  String? zMW,
  String? zWL,
  }) = _Symbols;


  factory Symbols.fromJson(Map<String, dynamic> json) =>
      _$SymbolsFromJson(json);
}