// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'currency_symbol_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_CurrencySymbolModel _$$_CurrencySymbolModelFromJson(
        Map<String, dynamic> json) =>
    _$_CurrencySymbolModel(
      success: json['success'] as bool?,
      symbols: json['symbols'] == null
          ? null
          : Symbols.fromJson(json['symbols'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$_CurrencySymbolModelToJson(
        _$_CurrencySymbolModel instance) =>
    <String, dynamic>{
      'success': instance.success,
      'symbols': instance.symbols,
    };

_$_Symbols _$$_SymbolsFromJson(Map<String, dynamic> json) => _$_Symbols(
      aED: json['aED'] as String?,
      aFN: json['aFN'] as String?,
      aLL: json['aLL'] as String?,
      aMD: json['aMD'] as String?,
      aNG: json['aNG'] as String?,
      aOA: json['aOA'] as String?,
      aRS: json['aRS'] as String?,
      aUD: json['aUD'] as String?,
      aWG: json['aWG'] as String?,
      aZN: json['aZN'] as String?,
      bAM: json['bAM'] as String?,
      bBD: json['bBD'] as String?,
      bDT: json['bDT'] as String?,
      bGN: json['bGN'] as String?,
      bHD: json['bHD'] as String?,
      bIF: json['bIF'] as String?,
      bMD: json['bMD'] as String?,
      bND: json['bND'] as String?,
      bOB: json['bOB'] as String?,
      bRL: json['bRL'] as String?,
      bSD: json['bSD'] as String?,
      bTC: json['bTC'] as String?,
      bTN: json['bTN'] as String?,
      bWP: json['bWP'] as String?,
      bYN: json['bYN'] as String?,
      bYR: json['bYR'] as String?,
      bZD: json['bZD'] as String?,
      cAD: json['cAD'] as String?,
      cDF: json['cDF'] as String?,
      cHF: json['cHF'] as String?,
      cLF: json['cLF'] as String?,
      cLP: json['cLP'] as String?,
      cNY: json['cNY'] as String?,
      cOP: json['cOP'] as String?,
      cRC: json['cRC'] as String?,
      cUC: json['cUC'] as String?,
      cUP: json['cUP'] as String?,
      cVE: json['cVE'] as String?,
      cZK: json['cZK'] as String?,
      dJF: json['dJF'] as String?,
      dKK: json['dKK'] as String?,
      dOP: json['dOP'] as String?,
      dZD: json['dZD'] as String?,
      eGP: json['eGP'] as String?,
      eRN: json['eRN'] as String?,
      eTB: json['eTB'] as String?,
      eUR: json['eUR'] as String?,
      fJD: json['fJD'] as String?,
      fKP: json['fKP'] as String?,
      gBP: json['gBP'] as String?,
      gEL: json['gEL'] as String?,
      gGP: json['gGP'] as String?,
      gHS: json['gHS'] as String?,
      gIP: json['gIP'] as String?,
      gMD: json['gMD'] as String?,
      gNF: json['gNF'] as String?,
      gTQ: json['gTQ'] as String?,
      gYD: json['gYD'] as String?,
      hKD: json['hKD'] as String?,
      hNL: json['hNL'] as String?,
      hRK: json['hRK'] as String?,
      hTG: json['hTG'] as String?,
      hUF: json['hUF'] as String?,
      iDR: json['iDR'] as String?,
      iLS: json['iLS'] as String?,
      iMP: json['iMP'] as String?,
      iNR: json['iNR'] as String?,
      iQD: json['iQD'] as String?,
      iRR: json['iRR'] as String?,
      iSK: json['iSK'] as String?,
      jEP: json['jEP'] as String?,
      jMD: json['jMD'] as String?,
      jOD: json['jOD'] as String?,
      jPY: json['jPY'] as String?,
      kES: json['kES'] as String?,
      kGS: json['kGS'] as String?,
      kHR: json['kHR'] as String?,
      kMF: json['kMF'] as String?,
      kPW: json['kPW'] as String?,
      kRW: json['kRW'] as String?,
      kWD: json['kWD'] as String?,
      kYD: json['kYD'] as String?,
      kZT: json['kZT'] as String?,
      lAK: json['lAK'] as String?,
      lBP: json['lBP'] as String?,
      lKR: json['lKR'] as String?,
      lRD: json['lRD'] as String?,
      lSL: json['lSL'] as String?,
      lTL: json['lTL'] as String?,
      lVL: json['lVL'] as String?,
      lYD: json['lYD'] as String?,
      mAD: json['mAD'] as String?,
      mDL: json['mDL'] as String?,
      mGA: json['mGA'] as String?,
      mKD: json['mKD'] as String?,
      mMK: json['mMK'] as String?,
      mNT: json['mNT'] as String?,
      mOP: json['mOP'] as String?,
      mRO: json['mRO'] as String?,
      mUR: json['mUR'] as String?,
      mVR: json['mVR'] as String?,
      mWK: json['mWK'] as String?,
      mXN: json['mXN'] as String?,
      mYR: json['mYR'] as String?,
      mZN: json['mZN'] as String?,
      nAD: json['nAD'] as String?,
      nGN: json['nGN'] as String?,
      nIO: json['nIO'] as String?,
      nOK: json['nOK'] as String?,
      nPR: json['nPR'] as String?,
      nZD: json['nZD'] as String?,
      oMR: json['oMR'] as String?,
      pAB: json['pAB'] as String?,
      pEN: json['pEN'] as String?,
      pGK: json['pGK'] as String?,
      pHP: json['pHP'] as String?,
      pKR: json['pKR'] as String?,
      pLN: json['pLN'] as String?,
      pYG: json['pYG'] as String?,
      qAR: json['qAR'] as String?,
      rON: json['rON'] as String?,
      rSD: json['rSD'] as String?,
      rUB: json['rUB'] as String?,
      rWF: json['rWF'] as String?,
      sAR: json['sAR'] as String?,
      sBD: json['sBD'] as String?,
      sCR: json['sCR'] as String?,
      sDG: json['sDG'] as String?,
      sEK: json['sEK'] as String?,
      sGD: json['sGD'] as String?,
      sHP: json['sHP'] as String?,
      sLL: json['sLL'] as String?,
      sOS: json['sOS'] as String?,
      sRD: json['sRD'] as String?,
      sTD: json['sTD'] as String?,
      sVC: json['sVC'] as String?,
      sYP: json['sYP'] as String?,
      sZL: json['sZL'] as String?,
      tHB: json['tHB'] as String?,
      tJS: json['tJS'] as String?,
      tMT: json['tMT'] as String?,
      tND: json['tND'] as String?,
      tOP: json['tOP'] as String?,
      tRY: json['tRY'] as String?,
      tTD: json['tTD'] as String?,
      tWD: json['tWD'] as String?,
      tZS: json['tZS'] as String?,
      uAH: json['uAH'] as String?,
      uGX: json['uGX'] as String?,
      uSD: json['uSD'] as String?,
      uYU: json['uYU'] as String?,
      uZS: json['uZS'] as String?,
      vEF: json['vEF'] as String?,
      vND: json['vND'] as String?,
      vUV: json['vUV'] as String?,
      wST: json['wST'] as String?,
      xAF: json['xAF'] as String?,
      xAG: json['xAG'] as String?,
      xAU: json['xAU'] as String?,
      xCD: json['xCD'] as String?,
      xDR: json['xDR'] as String?,
      xOF: json['xOF'] as String?,
      xPF: json['xPF'] as String?,
      yER: json['yER'] as String?,
      zAR: json['zAR'] as String?,
      zMK: json['zMK'] as String?,
      zMW: json['zMW'] as String?,
      zWL: json['zWL'] as String?,
    );

Map<String, dynamic> _$$_SymbolsToJson(_$_Symbols instance) =>
    <String, dynamic>{
      'aED': instance.aED,
      'aFN': instance.aFN,
      'aLL': instance.aLL,
      'aMD': instance.aMD,
      'aNG': instance.aNG,
      'aOA': instance.aOA,
      'aRS': instance.aRS,
      'aUD': instance.aUD,
      'aWG': instance.aWG,
      'aZN': instance.aZN,
      'bAM': instance.bAM,
      'bBD': instance.bBD,
      'bDT': instance.bDT,
      'bGN': instance.bGN,
      'bHD': instance.bHD,
      'bIF': instance.bIF,
      'bMD': instance.bMD,
      'bND': instance.bND,
      'bOB': instance.bOB,
      'bRL': instance.bRL,
      'bSD': instance.bSD,
      'bTC': instance.bTC,
      'bTN': instance.bTN,
      'bWP': instance.bWP,
      'bYN': instance.bYN,
      'bYR': instance.bYR,
      'bZD': instance.bZD,
      'cAD': instance.cAD,
      'cDF': instance.cDF,
      'cHF': instance.cHF,
      'cLF': instance.cLF,
      'cLP': instance.cLP,
      'cNY': instance.cNY,
      'cOP': instance.cOP,
      'cRC': instance.cRC,
      'cUC': instance.cUC,
      'cUP': instance.cUP,
      'cVE': instance.cVE,
      'cZK': instance.cZK,
      'dJF': instance.dJF,
      'dKK': instance.dKK,
      'dOP': instance.dOP,
      'dZD': instance.dZD,
      'eGP': instance.eGP,
      'eRN': instance.eRN,
      'eTB': instance.eTB,
      'eUR': instance.eUR,
      'fJD': instance.fJD,
      'fKP': instance.fKP,
      'gBP': instance.gBP,
      'gEL': instance.gEL,
      'gGP': instance.gGP,
      'gHS': instance.gHS,
      'gIP': instance.gIP,
      'gMD': instance.gMD,
      'gNF': instance.gNF,
      'gTQ': instance.gTQ,
      'gYD': instance.gYD,
      'hKD': instance.hKD,
      'hNL': instance.hNL,
      'hRK': instance.hRK,
      'hTG': instance.hTG,
      'hUF': instance.hUF,
      'iDR': instance.iDR,
      'iLS': instance.iLS,
      'iMP': instance.iMP,
      'iNR': instance.iNR,
      'iQD': instance.iQD,
      'iRR': instance.iRR,
      'iSK': instance.iSK,
      'jEP': instance.jEP,
      'jMD': instance.jMD,
      'jOD': instance.jOD,
      'jPY': instance.jPY,
      'kES': instance.kES,
      'kGS': instance.kGS,
      'kHR': instance.kHR,
      'kMF': instance.kMF,
      'kPW': instance.kPW,
      'kRW': instance.kRW,
      'kWD': instance.kWD,
      'kYD': instance.kYD,
      'kZT': instance.kZT,
      'lAK': instance.lAK,
      'lBP': instance.lBP,
      'lKR': instance.lKR,
      'lRD': instance.lRD,
      'lSL': instance.lSL,
      'lTL': instance.lTL,
      'lVL': instance.lVL,
      'lYD': instance.lYD,
      'mAD': instance.mAD,
      'mDL': instance.mDL,
      'mGA': instance.mGA,
      'mKD': instance.mKD,
      'mMK': instance.mMK,
      'mNT': instance.mNT,
      'mOP': instance.mOP,
      'mRO': instance.mRO,
      'mUR': instance.mUR,
      'mVR': instance.mVR,
      'mWK': instance.mWK,
      'mXN': instance.mXN,
      'mYR': instance.mYR,
      'mZN': instance.mZN,
      'nAD': instance.nAD,
      'nGN': instance.nGN,
      'nIO': instance.nIO,
      'nOK': instance.nOK,
      'nPR': instance.nPR,
      'nZD': instance.nZD,
      'oMR': instance.oMR,
      'pAB': instance.pAB,
      'pEN': instance.pEN,
      'pGK': instance.pGK,
      'pHP': instance.pHP,
      'pKR': instance.pKR,
      'pLN': instance.pLN,
      'pYG': instance.pYG,
      'qAR': instance.qAR,
      'rON': instance.rON,
      'rSD': instance.rSD,
      'rUB': instance.rUB,
      'rWF': instance.rWF,
      'sAR': instance.sAR,
      'sBD': instance.sBD,
      'sCR': instance.sCR,
      'sDG': instance.sDG,
      'sEK': instance.sEK,
      'sGD': instance.sGD,
      'sHP': instance.sHP,
      'sLL': instance.sLL,
      'sOS': instance.sOS,
      'sRD': instance.sRD,
      'sTD': instance.sTD,
      'sVC': instance.sVC,
      'sYP': instance.sYP,
      'sZL': instance.sZL,
      'tHB': instance.tHB,
      'tJS': instance.tJS,
      'tMT': instance.tMT,
      'tND': instance.tND,
      'tOP': instance.tOP,
      'tRY': instance.tRY,
      'tTD': instance.tTD,
      'tWD': instance.tWD,
      'tZS': instance.tZS,
      'uAH': instance.uAH,
      'uGX': instance.uGX,
      'uSD': instance.uSD,
      'uYU': instance.uYU,
      'uZS': instance.uZS,
      'vEF': instance.vEF,
      'vND': instance.vND,
      'vUV': instance.vUV,
      'wST': instance.wST,
      'xAF': instance.xAF,
      'xAG': instance.xAG,
      'xAU': instance.xAU,
      'xCD': instance.xCD,
      'xDR': instance.xDR,
      'xOF': instance.xOF,
      'xPF': instance.xPF,
      'yER': instance.yER,
      'zAR': instance.zAR,
      'zMK': instance.zMK,
      'zMW': instance.zMW,
      'zWL': instance.zWL,
    };
